name: Build MWAN3 & luci-app-mwan3 APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Jakarta

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Alpine chroot & abuild tools
      run: |
        sudo apt-get update
        sudo apt-get install -y alpine-chroot-install fakeroot

    - name: Set up Alpine chroot
      run: |
        sudo alpine-chroot-install --arch x86_64 /alpine
        sudo chroot /alpine apk update
        sudo chroot /alpine apk add alpine-sdk abuild sudo

    - name: Prepare abuild (setup keys, user, etc)
      run: |
        sudo chroot /alpine adduser -D builder
        echo "builder ALL=(ALL) NOPASSWD:ALL" | sudo tee /alpine/etc/sudoers.d/builder
        sudo chroot /alpine abuild-keygen -a -i -n

    - name: Copy aports to chroot
      run: |
        sudo mkdir -p /alpine/home/builder/aports
        sudo cp -r $GITHUB_WORKSPACE/aports/* /alpine/home/builder/aports/
        sudo chown -R builder:builder /alpine/home/builder/aports

    - name: Build MWAN3
      run: |
        sudo chroot --userspec builder:builder /alpine \
          sh -c "cd /home/builder/aports/community/mwan3 && abuild -r"

    - name: Build luci-app-mwan3
      run: |
        sudo chroot --userspec builder:builder /alpine \
          sh -c "cd /home/builder/aports/community/luci-app-mwan3 && abuild -r"

    - name: Upload MWAN3 & luci-app-mwan3 APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mwan3-luci-app-mwan3-apk
        path: |
          /alpine/home/builder/packages/community/x86_64/mwan3-*.apk
          /alpine/home/builder/packages/community/x86_64/luci-app-mwan3-*.apk
