name: Build OpenWrt 22.03.0 (x86/64) Image Builder

# Workflow ini bisa dijalankan secara manual dari tab Actions di GitHub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Install Dependencies (Sesuai Permintaan)
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: 3. Download and Extract OpenWrt Image Builder
        run: |
          wget https://archive.openwrt.org/releases/22.03.0/targets/x86/64/openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64.tar.xz
          tar -xJvf openwrt-imagebuilder-*.tar.xz
          cd openwrt-imagebuilder-*/

      - name: 4. Build Firmware Image
        run: |
          # Masuk ke direktori image builder
          cd openwrt-imagebuilder-*/

          # Daftar paket yang akan di-install
          PACKAGES="luci luci-ssl-openssl opennds freeradius3 kmod-ath9k wpad-openssl rp-ppoe-server luci-app-opennds nano htop"

          # Jalankan perintah build
          make image \
            PROFILE="generic" \
            PACKAGES="${PACKAGES}"

      - name: 5. Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-22.03.0-x86_64-firmware
          # Path hasil build image
          path: openwrt-imagebuilder-*/bin/targets/x86/64/*.img.gz
          
