# Nama workflow
name: Build OpenWrt 22.03.0 (x86/64) - Full Stack Captive Portal

# Pemicu workflow: dapat dijalankan secara manual dari tab Actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode (diperlukan oleh Actions)
      - name: 1. Checkout
        uses: actions/checkout@v4

      # Langkah 2: Instal dependensi untuk proses build
      - name: 2. Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      # Langkah 3: Build Firmware dengan semua paket kustom
      - name: 3. Build Firmware Image
        run: |
          # Tentukan nama direktori builder
          BUILDER_DIR="openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64"

          # Unduh dan ekstrak Image Builder
          wget https://archive.openwrt.org/releases/22.03.0/targets/x86/64/${BUILDER_DIR}.tar.xz
          tar -xJvf ${BUILDER_DIR}.tar.xz

          # Masuk ke direktori Image Builder
          cd ${BUILDER_DIR}

          # === DAFTAR LENGKAP PAKET YANG AKAN DI-INSTALL ===
          PACKAGES="\
          # Hapus paket SSL default untuk menghindari konflik
          -wpad-basic-wolfssl -libwolfssl -libustream-wolfssl \
          \
          # Paket Dasar dan Kernel Module
          Base-files ca-bundle dnsmasq-full dropbear e2fsprogs firewall4 fstools grub2-bios-setup \
          kmod-button-hotplug kmod-nft-offload libc libgcc logd mkf2fs mtd netifd nftables \
          odhcp6c odhcpd-ipv6only opkg partx-utils ppp ppp-mod-pppoe procd-ujail uci uclient-fetch \
          urandom-seed urngd kmod-amazon-ena kmod-amd-xgbe kmod-bnx2 kmod-dwmac-intel kmod-e1000e \
          kmod-e1000 kmod-forcedeth kmod-fs-vfat kmod-igb kmod-igc kmod-ixgbe kmod-r8169 kmod-tg3 \
          kmod-drm-i915 nano \
          \
          # LuCI & Tema
          luci luci-theme-argon luci-app-argon-config \
          \
          # Web Server Stack (Nginx + PHP)
          nginx nginx-mod-luci \
          php8 php8-cli php8-cgi php8-fpm php8-fastcgi \
          \
          # Module PHP Penting untuk RadiusDesk & Aplikasi Web Lain
          php8-mod-session php8-mod-json php8-mod-mysqli php8-mod-pdo php8-mod-pdo-mysql \
          \
          # Database Server untuk RadiusDesk
          mariadb-server mariadb-client \
          \
          # Wireless & Otentikasi
          kmod-ath9k wpad-openssl \
          \
          # Captive Portal
          opennds \
          \
          # RADIUS Server
          freeradius3 freeradius3-utils freeradius3-default \
          "
          # =========================================================

          # Jalankan perintah 'make' untuk membuat image firmware
          make image PROFILE="generic" PACKAGES="${PACKAGES}"

      # Langkah 4: Unggah hasil build sebagai artifact
      - name: 4. Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-full-captive-portal-firmware
          path: openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64/bin/targets/x86/64/*.img.gz
          
