name: Build OpenWrt 22.03.0 (x86/64) Image Builder

# Workflow ini bisa dijalankan secara manual dari tab Actions di GitHub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync \
            unzip zlib1g-dev file wget

      - name: 3. Download and Extract OpenWrt Image Builder
        run: |
          wget https://archive.openwrt.org/releases/22.03.0/targets/x86/64/openwrt-imagebuilder-22.03.0-x86-64.Linux-x86_64.tar.xz
          tar -xJvf openwrt-imagebuilder-*.tar.xz
          # Masuk ke direktori hasil ekstrak
          cd openwrt-imagebuilder-*/
          # Menambahkan feed custom jika diperlukan (opsional)
          # echo 'src-git custom_feed https://github.com/user/repo.git' >> repositories.conf
          # make clean

      - name: 4. Build Firmware Image
        run: |
          # Masuk ke direktori image builder
          cd openwrt-imagebuilder-*/

          # Daftar paket yang akan di-install. Pisahkan dengan spasi.
          # LuCI, SSL, OpenNDS, FreeRADIUS3, Driver Ath9k, WPAD, PPPoE Server, dll.
          PACKAGES="luci luci-ssl-openssl opennds freeradius3 kmod-ath9k wpad-openssl rp-pppoe-server luci-app-opennds nano htop"

          # Jalankan perintah build
          make image \
            PROFILE="generic" \
            PACKAGES="${PACKAGES}"

      - name: 5. Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-22.03.0-x86_64-firmware
          # Path hasil build image
          path: openwrt-imagebuilder-*/bin/targets/x86/64/*.img.gz
