name: Build OpenWrt x86_64 RTRWNet

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout OpenWrt
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        ref: v24.05.0-rc2 # Ganti dengan tag/release sesuai kebutuhan

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex g++ gawk gcc-multilib git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync unzip zlib1g-dev file wget

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure target and packages
      run: |
        cp feeds.conf.default feeds.conf
        make defconfig
        # Tambahkan paket-paket kebutuhan RTRW Net
        cat >>.config <<EOF

        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y

        CONFIG_PACKAGE_kmod-ath9k=y
        CONFIG_PACKAGE_opennds=y
        CONFIG_PACKAGE_wpad-openssl=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-app-firewall=y
        CONFIG_PACKAGE_luci-app-opennds=y
        CONFIG_PACKAGE_iptables=y
        CONFIG_PACKAGE_ip-full=y
        CONFIG_PACKAGE_ppp=y
        CONFIG_PACKAGE_pppoe=y
        CONFIG_PACKAGE_pppoe-server=y
        CONFIG_PACKAGE_uhttpd=y
        CONFIG_PACKAGE_firewall4=y
        # Tambahkan paket lain sesuai kebutuhan

        EOF

        make defconfig

    - name: Download sources
      run: make download -j8

    - name: Build firmware
      run: make -j$(nproc) V=s

    - name: Collect firmware images
      if: success()
      run: |
        mkdir -p output
        find bin/targets/ -type f -name '*combined*img*' -or -name '*vmlinuz*' -or -name '*rootfs*' | xargs -I{} cp {} output/

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86_64-firmware
        path: output/
