name: Build OpenWrt RTRWNet x86_64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex g++ gawk gcc-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-pyelftools python3-setuptools python3-pip rsync unzip zlib1g-dev file wget libelf-dev ecj subversion

    - name: Clone OpenWrt
      run: |
        git clone --depth 1 https://github.com/openwrt/openwrt.git -b v24.05.0 openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Replace/extend feeds for theme Argon, openNDS, freeradius3, daloradius
      run: |
        cd openwrt
        # Theme Argon
        git clone --depth 1 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

        # openNDS (jika belum ada di feeds, override)
        git clone --depth 1 https://github.com/openNDS/openNDS.git package/opennds

        # daloradius (Web untuk Freeradius, biasanya manual install, contoh fetch)
        wget https://github.com/lirantal/daloradius/archive/refs/heads/master.zip -O daloradius.zip
        unzip daloradius.zip -d package/
        mv package/daloradius-master package/daloradius

    - name: Create custom config
      run: |
        cd openwrt
        cat <<EOF > .config
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_Generic=y

        # LuCI
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-ssl=y
        CONFIG_PACKAGE_luci-theme-argon=y
        CONFIG_PACKAGE_luci-app-firewall=y

        # Network Tools
        CONFIG_PACKAGE_iptables=y
        CONFIG_PACKAGE_iptables-mod-tproxy=y
        CONFIG_PACKAGE_ppp=y
        CONFIG_PACKAGE_pppoe=y
        CONFIG_PACKAGE_wireguard=y

        # RTRWNet Essentials
        CONFIG_PACKAGE_dhcpdump=y
        CONFIG_PACKAGE_ddns-scripts=y
        CONFIG_PACKAGE_ddns-scripts-cloudflare=y
        CONFIG_PACKAGE_adblock=y
        CONFIG_PACKAGE_uhttpd=y
        CONFIG_PACKAGE_vsftpd=y
        CONFIG_PACKAGE_samba4-server=y
        CONFIG_PACKAGE_nftables=y

        # openNDS, Freeradius3, Daloradius
        CONFIG_PACKAGE_opennds=y
        CONFIG_PACKAGE_freeradius3=y
        CONFIG_PACKAGE_php7=y
        CONFIG_PACKAGE_php7-cgi=y
        CONFIG_PACKAGE_php7-mod-mysqli=y
        CONFIG_PACKAGE_php7-mod-gd=y
        CONFIG_PACKAGE_php7-mod-json=y
        CONFIG_PACKAGE_php7-mod-session=y
        CONFIG_PACKAGE_php7-mod-curl=y
        CONFIG_PACKAGE_mariadb-server=y
        CONFIG_PACKAGE_mariadb-client=y
        CONFIG_PACKAGE_apache=y

        # Utilities
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_screen=y
        CONFIG_PACKAGE_wget=y
        CONFIG_PACKAGE_curl=y

        # Add more packages as needed...
        EOF

    - name: Build firmware
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc) || make download -j1 V=s
        make -j$(nproc) V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86_64-RTRWNET
        path: openwrt/bin/targets/x86/64/*.img.gz
