name: Build OpenWrt x86_64 RTRWNet & Wifi Voucher (Auto WiFi, Argon Theme)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Jakarta

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils python3-pyelftools \
          rsync unzip zlib1g-dev file wget python3 python3-pip python3-setuptools \
          subversion swig time

    - name: Download OpenWrt source
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add opennds package
      run: |
        cd openwrt/package
        git clone https://github.com/opennds/opennds.git

    - name: Add luci-theme-argon
      run: |
        cd openwrt/package
        git clone https://github.com/jerrykuku/luci-theme-argon.git

    - name: Create default .config with required packages
      run: |
        cd openwrt
        cat <<EOF > .config
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_Generic=y

        # WiFi & Security
        CONFIG_PACKAGE_kmod-ath9k=y
        CONFIG_PACKAGE_wpad-openssl=y

        # LuCI & Theme
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-theme-argon=y

        # opennds
        CONFIG_PACKAGE_opennds=y

        # Utility
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_htop=y
        EOF
        make defconfig
    - name: Enable WiFi by default (uci-defaults script)
      run: |
       mkdir -p openwrt/files/etc/uci-defaults
        cat <<'EOW' > openwrt/files/etc/uci-defaults/99-wifi-on
        #!/bin/sh
        uci set wireless.@wifi-device[0].disabled=0
        uci set wireless.@wifi-iface[0].ssid='OpenWrt'
        uci set wireless.@wifi-iface[0].encryption='psk2'
        uci set wireless.@wifi-iface[0].key='passwordwifi'
        uci commit wireless
        wifi reload
       EOW
       chmod +x openwrt/files/etc/uci-defaults/99-wifi-on

    - name: Build OpenWrt (x86_64, multicore)
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc) download
        make -j$(nproc) V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x86_64-firmware
        path: openwrt/bin/targets/x86/64/*.img.gz

    - name: Upload opennds package
      uses: actions/upload-artifact@v4
      with:
        name: opennds-ipk
        path: openwrt/bin/packages/x86_64/*/opennds*.ipk
